# Numpy - Exercices

Voici une série de tests pour vérifier ses connaissances en Numpy. Le but est que cette bibliothèque et la programmation vectorielle qu'elle implique deviennent naturelles. Il faut oublier la programmation classique avec des boucles (il ne faut pas utiliser de boucle `for` ou autre dans cette feuille en dehors de construction de [liste en compréhension](../../lesson1%20Python%20basics/03%20-%20Tests%20et%20boucles.ipynb) ).

Les fonctions ne doivent jamais modifier les arguements.

Les exercices indique le nombre de ligne de la réponse. Cela comprend l'en-tête de la fonction lorsqu'il y en a une.

Pensez à tester vos résultats.

# Numpy - Exercises

Here is a series of tests to check your knowledge in Numpy. The goal is for this library and the vectorized programming it implies to become natural. You should forget about classic programming with loops (do not use a `for` loop or anything else in this notebook except for list comprehension).

Functions should never modify their arguments.

The exercises indicate the number of lines in the answer. This includes the function header when there is one.

Remember to test your results.

In [1]:
import numpy as np
rand = np.random.RandomState(123)

A = np.arange(12).reshape(3,4)
B = rand.randint(-10, 10, size=(5,5))
print(A, '\n')
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[  3  -8  -8  -4   7]
 [  9   0  -9 -10   7]
 [  5  -1 -10   4 -10]
 [  5   9   4  -6 -10]
 [  6  -6   7  -7  -8]]


### Matrice carrée

Créer la matrice carrée 5x5 qui contient les 25 premiers entiers, de 1 à 25.

1 ligne

### Square Matrix

Create the 5x5 square matrix containing the first 25 integers, from 1 to 25.

1 line

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Norme d'un vecteur

Retourner la norme euclidienne d'un vecteur sans utiliser la fonction `norm`.

2 lignes

### Vector Norm

Return the Euclidean norm of a vector without using the `norm` function.

2 lines

In [3]:
def norm(v):
    

### Sous-matrice

Extraire la sous-matrice de taille (n-2)x(m-2) qui retire les bords de la matrice A de taille nxm.

2 lignes

### Sub-Matrix

Extract the sub-matrix of size (n-2)x(m-2) that removes the borders of the nxm matrix A.

2 lines

In [4]:
def submat(A):


### Vecteur aléatoire

Lorsqu'on fait un petit tirage entre -a et a, il est probablement que la moyenne ne soit pas à 0. Aussi on veut créer une fonction qui prend une taille n et retourne un vecteur  d'entiers aléatoire de taille n compris presque entre -a et +a et centré presque en 0.

3 lignes

### Random Vector

Small set of random value between -a and a will not be zero centered. Create a function that takes a size n and returns a random integer vector of size n almost between -a and +a and centered as close as possible to 0.

3 lines

In [5]:
def rand_vec(n, a):



### Trace

Retourner la trace d'une matrice sans utiliser la fonction `trace` (à vous de chercher les éléments qui vous manque).

2 lignes

### Trace

Return the trace of a matrix without using the `trace` function (you have to find the missing elements yourself).

2 lines

In [6]:
def trace(A):
 

### Matrice de multiples de 3

Arrondir la matrice donnée au multiple de 3 le plus proche (pour chaque valeur).

2 lignes

### Matrix of Multiples of 3

Round the given matrix to the nearest multiple of 3 (for each value).

2 lines

In [7]:
def round3(A):


### Nombre de 9

Compter le nombre de 9 dans une matrice d'entier A donnée en paramètre.

2 lignes

### Count of 9s

Count the number of 9s in an integer matrix A given as a parameter.

2 lines

In [8]:
def nb9(A):


### Colonne qui a la plus petite moyenne

Retourner l'indice de la colonne d'une matrice ayant la plus petite moyenne.

2 lignes

### Column with the Smallest Average

Return the index of the column of a matrix with the smallest average.

2 lines

In [9]:
def min_col_mean(A):


### ChessSum

On regarde la matrice comme un échequier avec des cases blanches et des cases noires qui alternent. La case en [0,0] est noire. 
Calculer la somme des valeurs sur les cases blanches.

2 lignes

### ChessSum

We consider the matrix as a chessboard with alternating white and black squares. The square at [0,0] is black. 
Calculate the sum of the values on the white squares.

2 lines

In [10]:
def chess_sum(A):


### 2 minimums

Retourner les 2 plus petites valeurs d'une matrice avec une méthode de complexité linéaire. Attention, si la matrice a sa valeur minimal en double, la réponse est deux fois cette valeur minimale.

6 lignes

### 2 Minimums

Return the 2 smallest values of a matrix using a method with linear complexity. Note that if the matrix has its minimum value duplicated, the answer is twice this minimum value.

6 lines

In [11]:
def mins(A):






### Lignes dans l'ordre

Ranger les lignes d'une matrice dans l'ordre croissant de leur moyenne.

2 lignes

### Rows in Order

Sort the rows of a matrix in ascending order of their average.

2 lines

In [12]:
def sort_lines(A):


### Valeurs uniques

Donner la liste des valeurs uniques (qui n'apparaissent qu'une fois) dans un tableau numpy (la fonction `unique` sera utile).

3 lignes

### Unique Values

Provide the list of unique values (appearing only once) in a numpy array (the `unique` function will be useful).

3 lines

In [13]:
def val_unique(A):



### Tenseur magique

Constuire un tenseur 3D de taille nxnxn en utilisant n fois les n² premiers entiers et de sorte que la sommme des éléments de chaque plan (coupe) est toujours la même.

3 lignes

### Magic Tensor

Construct a 3D tensor of size nxnxn using n times the first n² integers and such that the sum of the elements of each plane (slice) is always the same.

3 lines

In [14]:
def mk_magic_tensor(n):



### Plans d'un tenseur

Extraire tous les plans d'un tenseur 3d. On retourne une liste de tableaux.

5 lignes (2 lignes avec la fonction `take`)

### Tensor Slices

Extract all the slices of a 3D tensor. We return a list of arrays.

5 lines (2 lines with the `take` function)

In [15]:
def extract_planes(T):



